'use strict';

/**
 * completion — shell completion scripts, generated from one description of
 * the CLI's surface.
 *
 * The alternative is two hand-written scripts that drift away from the tool
 * and from each other the first time a flag is added. Here the commands,
 * their flags and the fixed values those flags accept are data; the bash and
 * zsh generators are two renderers over it, exactly like the ASCII and SVG
 * graph renderers are two views of one layout.
 *
 * No completion library, and nothing to install: `repotool completion bash`
 * prints a script, and the shell evaluates it.
 */

/** Options every command accepts. */
const GLOBAL_FLAGS = ['--repo', '--color', '--no-color', '--help'];

/**
 * Per-command flags, and the fixed set of values a flag accepts where one
 * exists. `path` and `dir` ask the shell for filename completion instead.
 */
const SPEC = {
  graph: {
    flags: ['--limit', '--branch', '--no-dates', '--format', '--output'],
    values: { '--format': ['ascii', 'svg'], '--output': 'path', '--branch': 'ref' },
  },
  stats: { flags: ['--limit', '--json'], values: {} },
  hotspots: {
    flags: ['--limit', '--sort', '--json'],
    values: { '--sort': ['score', 'commits', 'churn', 'authors'] },
  },
  ask: { flags: ['--json'], values: {} },
  diff: { flags: ['--context', '--stat'], values: {} },
  completion: { flags: [], values: {} },
  help: { flags: [], values: {} },
};

const SHELLS = ['bash', 'zsh'];

/** Command names in a stable order, so regenerating gives the same script. */
function commandNames() {
  return Object.keys(SPEC);
}

/** Every flag a command understands, its own plus the global ones. */
function flagsFor(command) {
  const own = SPEC[command] ? SPEC[command].flags : [];
  return [...own, ...GLOBAL_FLAGS];
}

/** Flags whose value comes from a fixed list, as `--flag:a b c` lines. */
function valueLines(command, separator) {
  const values = (SPEC[command] || {}).values || {};
  return Object.entries(values)
    .filter(([, value]) => Array.isArray(value))
    .map(([flag, list]) => `${flag}${separator}${list.join(' ')}`);
}

/**
 * bash: one function, registered with `complete -F`.
 *
 * The logic is deliberately flat — look at the previous word to see whether
 * we are completing a flag's value, otherwise complete a command or a flag.
 */
function bashScript() {
  const commands = commandNames();

  const valueCases = [];
  for (const command of commands) {
    const values = (SPEC[command] || {}).values || {};
    for (const [flag, list] of Object.entries(values)) {
      if (!Array.isArray(list)) continue;
      valueCases.push(`      ${flag}) COMPREPLY=( $(compgen -W "${list.join(' ')}" -- "$current") ); return 0 ;;`);
    }
  }
  // A flag can appear under more than one command; bash sees only the word
  // before the cursor, so we collapse duplicates and keep the first case.
  const seen = new Set();
  const uniqueValueCases = valueCases.filter((line) => {
    const flag = line.trim().split(')')[0];
    if (seen.has(flag)) return false;
    seen.add(flag);
    return true;
  });

  const commandCases = commands.map(
    (command) => `    ${command}) flags="${flagsFor(command).join(' ')}" ;;`,
  );

  return `# repotool bash completion — generated by \`repotool completion bash\`
# Install:  eval "$(repotool completion bash)"
_repotool() {
  local current previous command flags
  current="\${COMP_WORDS[COMP_CWORD]}"
  previous="\${COMP_WORDS[COMP_CWORD-1]}"

  # A flag that takes a value: complete the value, not another flag.
  case "$previous" in
${uniqueValueCases.join('\n')}
      --repo) COMPREPLY=( $(compgen -d -- "$current") ); return 0 ;;
      --output) COMPREPLY=( $(compgen -f -- "$current") ); return 0 ;;
      --limit|--context) return 0 ;;
  esac

  # The first non-flag word is the command.
  command=""
  local i
  for ((i = 1; i < COMP_CWORD; i++)); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) command="\${COMP_WORDS[i]}"; break ;;
    esac
  done

  if [ -z "$command" ]; then
    COMPREPLY=( $(compgen -W "${commands.join(' ')}" -- "$current") )
    return 0
  fi

  if [ "$command" = "completion" ]; then
    COMPREPLY=( $(compgen -W "${SHELLS.join(' ')}" -- "$current") )
    return 0
  fi

  if [ "$command" = "help" ]; then
    COMPREPLY=( $(compgen -W "${commands.join(' ')}" -- "$current") )
    return 0
  fi

  flags="${GLOBAL_FLAGS.join(' ')}"
  case "$command" in
${commandCases.join('\n')}
  esac

  COMPREPLY=( $(compgen -W "$flags" -- "$current") )
  return 0
}
complete -F _repotool repotool
`;
}

/**
 * zsh: the same model, expressed with zsh's own completion builtins.
 *
 * We stay with `compadd` rather than `_arguments` specs: it is less clever,
 * but it is one code path for every command and it needs no compinit-time
 * argument grammar to keep in step with the bash version.
 */
function zshScript() {
  const commands = commandNames();

  const valueCases = [];
  const seen = new Set();
  for (const command of commands) {
    for (const line of valueLines(command, ':')) {
      const [flag, list] = line.split(':');
      if (seen.has(flag)) continue;
      seen.add(flag);
      valueCases.push(`      ${flag}) compadd -- ${list}; return 0 ;;`);
    }
  }

  const commandCases = commands.map(
    (command) => `    ${command}) flags=(${flagsFor(command).join(' ')}) ;;`,
  );

  return `#compdef repotool
# repotool zsh completion — generated by \`repotool completion zsh\`
# Install:  repotool completion zsh > "\${fpath[1]}/_repotool"
_repotool() {
  local current previous command
  local -a flags
  current="\${words[CURRENT]}"
  previous="\${words[CURRENT-1]}"

  case "$previous" in
${valueCases.join('\n')}
      --repo) _files -/; return 0 ;;
      --output) _files; return 0 ;;
      --limit|--context) return 0 ;;
  esac

  command=""
  local word
  for word in \${words[2,CURRENT-1]}; do
    case "$word" in
      -*) ;;
      *) command="$word"; break ;;
    esac
  done

  if [[ -z "$command" ]]; then
    compadd -- ${commands.join(' ')}
    return 0
  fi

  case "$command" in
    completion) compadd -- ${SHELLS.join(' ')}; return 0 ;;
    help) compadd -- ${commands.join(' ')}; return 0 ;;
  esac

  flags=(${GLOBAL_FLAGS.join(' ')})
  case "$command" in
${commandCases.join('\n')}
  esac

  compadd -- \${flags[@]}
  return 0
}
_repotool "$@"
`;
}

/** Script for a named shell, or null when we do not generate one for it. */
function completionScript(shell) {
  if (shell === 'bash') return bashScript();
  if (shell === 'zsh') return zshScript();
  return null;
}

module.exports = { completionScript, bashScript, zshScript, SHELLS, SPEC, GLOBAL_FLAGS, commandNames };
